### ISSUE TITLE
[Phulwari][Support] Add a new phulwari

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/jss#5]
https://docs.google.com/spreadsheets/d/1L6lbfw9uVt-HcwJbK9esmwr90Gh08S8euHJuHQuqdt8/edit#gid=614629195
Catchment - Alwar
Gram Panchayat - Lamsarai
Village - Lamsarai
Phulwari - Maharantola

https://openchs.freshdesk.com/a/tickets/445

**Comment by sidsamanvay** [comment]
@garimadosar5 
These locations are there right now: 
Lamsarai (Near Ahirwar)
Lamsarai (Near Keshwani)

which one to map the phulwari to?
